name: Convert Excel to JSON

on:
  push:
    paths:
      - 'data/locations.xlsx'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pandas openpyxl

    - name: Run converter script
      run: python scripts/convert_excel_to_json.py

    - name: Commit JSON
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add data/locations.json
        git commit -m "Update JSON data vanuit Excel" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
