name: Excel to JSON

on:
  push:
    paths:
      - 'data/*.xlsx'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Convert Excel to JSON
        run: |
          python convert_excel_to_json.py
          
      - name: Commit JSON output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/locations.json
          git commit -m "Update locations.json from Excel"
          git push
